### ISSUE TITLE
Menu error

### ISSUE THREAD

**Issue by danaukes** [gios-asu/ASU-Web-Standards-Jekyll-Theme#3]
I noticed in the most recent commit that the menu now occludes the header; the original commit did not do this.  Reverting to the previous commit fixed it for me.

**Comment by idmontie** [comment]
Which header are you referring to? The ASU Jekyll header file has only two lines that changes in the last commit.

**Comment by danaukes** [comment]
I'm not saying the issue is in the header file,but a change in the
stylesheet or JavaScript may be causing the menu to be in the wrong
place....try a Jekyll serve and you will see

**Comment by danaukes** [comment]
thanks!
