### ISSUE TITLE
Footer out of spec.

### ISSUE THREAD

**Issue by danaukes** [gios-asu/ASU-Web-Standards-Jekyll-Theme#4]
I notice that this template diverges from the branding guide in terms of the current footer spec, found [here](https://brandguide.asu.edu/web-standards/enterprise/global-asu-footer).  Any plans to continue updating this template?  I use jekyll and would love to use this, but I don't want ASU to come down on any sites I develop with this.

**Comment by rraub** [comment]
We are going to maintain this theme for the foreseeable future. 

The footer we have here hasn't been documented on brandguide yet, but it is accepted and the documentation is forthcoming.

**Comment by danaukes** [comment]
great, thanks!  I was worried I would have to somehow bridge the gap across
multiple themes.

**Comment by rraub** [comment]
FYI: We are maintaining all of our ASU Standards in this [reusable bootstrap theme](https://github.com/gios-asu/ASU-Web-Standards-Bootstrap) which this Jekyll theme uses, so if you have any questions on this implementation of the  standards feel free to post an issue there.
